//! Dead-letter records retained for failed inbound event handling and replay workflows.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use time::PrimitiveDateTime;

use crate::domain::shared::ids::{DeadLetterId, EventId};

/// Enumerates the replay states allowed for an inbound dead-letter row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DeadLetterReplayStatus {
    /// The dead-letter row is pending replay or manual recovery.
    Pending,
    /// The dead-letter row was replayed successfully.
    Replayed,
    /// The dead-letter row was intentionally ignored after review.
    Ignored,
}

impl DeadLetterReplayStatus {
    /// Parses the persisted database string into the typed replay status enum.
    pub fn from_db(value: &str) -> Option<Self> {
        match value {
            "pending" => Some(Self::Pending),
            "replayed" => Some(Self::Replayed),
            "ignored" => Some(Self::Ignored),
            _ => None,
        }
    }

    /// Returns the canonical persisted string for the replay status enum.
    pub fn as_db(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Replayed => "replayed",
            Self::Ignored => "ignored",
        }
    }
}

/// Represents a failed inbound event retained for later replay or diagnosis.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InboundDeadLetter {
    /// Stable dead-letter row identifier generated by identity.
    pub dead_letter_id: DeadLetterId,
    /// Optional source event id retained when parsing reached envelope level.
    pub source_event_id: Option<EventId>,
    /// Source module that emitted the inbound event.
    pub source_module: String,
    /// Event type retained for replay routing and diagnostics.
    pub event_type: String,
    /// Raw payload snapshot retained for manual or automated replay.
    pub payload_json: Value,
    /// Failure reason recorded when the event entered the dead-letter table.
    pub failure_reason: String,
    /// Current replay disposition for the dead-letter row.
    pub replay_status: DeadLetterReplayStatus,
    /// Timestamp when the row was captured.
    pub created_at: PrimitiveDateTime,
}
