//! Global member write-model aggregate used by repository and command layers.

use serde::{Deserialize, Serialize};
use time::{OffsetDateTime, PrimitiveDateTime};

use crate::domain::role_catalog::RoleCatalogEntry;
use crate::domain::shared::context::ActorContext;
use crate::domain::shared::ids::{CapabilityProfileId, GlobalMemberId, MemoryRefsId, RoleId};
use crate::error::IdentityError;

/// Enumerates the only lifecycle states allowed for a global member write model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GlobalMemberLifecycle {
    /// Initial lifecycle immediately after explicit member creation.
    Hired,
    /// Member is available for normal platform collaboration.
    Active,
    /// Member is temporarily paused from new collaboration.
    Paused,
    /// Member is retired from standard collaboration but still retained as truth.
    Retired,
    /// Member has entered the irreversible tombstoned terminal state.
    Tombstoned,
}

impl GlobalMemberLifecycle {
    /// Returns the initial lifecycle assigned during explicit member creation.
    pub fn initial_hired() -> Self {
        Self::Hired
    }

    /// Parses a persisted lifecycle string into the strongly-typed lifecycle enum.
    pub fn from_db(value: &str) -> Option<Self> {
        match value {
            "hired" => Some(Self::Hired),
            "active" => Some(Self::Active),
            "paused" => Some(Self::Paused),
            "retired" => Some(Self::Retired),
            "tombstoned" => Some(Self::Tombstoned),
            _ => None,
        }
    }

    /// Returns the canonical database representation of the lifecycle enum.
    pub fn as_db(self) -> &'static str {
        match self {
            Self::Hired => "hired",
            Self::Active => "active",
            Self::Paused => "paused",
            Self::Retired => "retired",
            Self::Tombstoned => "tombstoned",
        }
    }

    /// Returns true when the lifecycle should be treated as terminal for ordinary writes.
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Retired | Self::Tombstoned)
    }
}

/// Represents the platform-level member identity truth persisted in `global_members`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GlobalMember {
    /// Stable global member identifier referenced by downstream modules.
    pub global_member_id: GlobalMemberId,
    /// User-facing display name kept in the identity write model.
    pub display_name: String,
    /// Current lifecycle state governed by the domain state machine.
    pub lifecycle: GlobalMemberLifecycle,
    /// Main role reference that must point at a valid role catalog entry.
    pub main_role_id: RoleId,
    /// Secondary role references stored as an ordered JSON array.
    pub secondary_role_ids: Vec<RoleId>,
    /// Optional capability profile reference linked after profile creation.
    pub capability_profile_id: Option<CapabilityProfileId>,
    /// Optional memory refs aggregate reference linked after memory setup.
    pub memory_refs_id: Option<MemoryRefsId>,
    /// Optimistic-lock version incremented on every successful save.
    pub version: i64,
    /// Trusted actor snapshot that originally created the member.
    pub created_by: ActorContext,
    /// Creation timestamp written once when the member is first created.
    pub created_at: PrimitiveDateTime,
    /// Last update timestamp refreshed whenever the write model changes.
    pub updated_at: PrimitiveDateTime,
}

/// Minimal explicit-create command consumed by the `HireGlobalMember` application service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HireGlobalMemberCommand {
    /// User-facing display name for the newly created member.
    pub display_name: String,
    /// Main role reference that must resolve to an active role catalog entry.
    pub main_role_id: RoleId,
    /// Optional ordered secondary role references to attach at creation time.
    pub secondary_role_ids: Vec<RoleId>,
}

/// Explicit lifecycle-change command consumed by the `UpdateLifecycle` application service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpdateLifecycleCommand {
    /// Stable global member id targeted by the lifecycle transition.
    pub global_member_id: GlobalMemberId,
    /// Destination lifecycle requested by the caller.
    pub target_lifecycle: GlobalMemberLifecycle,
    /// Human-readable reason retained in audit and outbox payloads.
    pub reason: String,
    /// Optional optimistic-lock version expected by the caller.
    pub expected_version: Option<i64>,
}

/// Summary returned directly from command write paths after member creation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GlobalMemberSummary {
    /// Stable global member id generated by identity.
    pub global_member_id: GlobalMemberId,
    /// User-facing display name captured in the write model.
    pub display_name: String,
    /// Current lifecycle after the command completed.
    pub lifecycle: GlobalMemberLifecycle,
    /// Current main role id retained by the member write model.
    pub main_role_id: RoleId,
    /// Current secondary role ids retained by the member write model.
    pub secondary_role_ids: Vec<RoleId>,
    /// Linked capability profile id when present.
    pub capability_profile_id: Option<CapabilityProfileId>,
    /// Linked memory refs id when present.
    pub memory_refs_id: Option<MemoryRefsId>,
}

impl GlobalMember {
    /// Creates a newly hired global member from the explicit-create command.
    ///
    /// # Errors
    ///
    /// Returns an error when the display name is blank after trimming or when the role entry
    /// does not match the requested main role id.
    pub fn hire(
        command: HireGlobalMemberCommand,
        role_entry: &RoleCatalogEntry,
        actor: ActorContext,
        global_member_id: GlobalMemberId,
        now: PrimitiveDateTime,
    ) -> Result<Self, IdentityError> {
        let display_name = command.display_name.trim();
        if display_name.is_empty() {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_INVALID_ARGUMENT",
                message: "display_name must not be blank".to_string(),
            });
        }

        if role_entry.role_id != command.main_role_id {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_ROLE_NOT_FOUND",
                message: format!(
                    "main role `{}` does not match the resolved role catalog entry",
                    command.main_role_id.as_str()
                ),
            });
        }

        Ok(Self {
            global_member_id,
            display_name: display_name.to_string(),
            lifecycle: GlobalMemberLifecycle::initial_hired(),
            main_role_id: command.main_role_id,
            secondary_role_ids: command.secondary_role_ids,
            capability_profile_id: None,
            memory_refs_id: None,
            version: 0,
            created_by: actor,
            created_at: now,
            updated_at: now,
        })
    }

    /// Returns true when the requested lifecycle is a legal ordinary transition.
    pub fn can_transition_to(&self, target_lifecycle: GlobalMemberLifecycle) -> bool {
        match (self.lifecycle, target_lifecycle) {
            (GlobalMemberLifecycle::Hired, GlobalMemberLifecycle::Active) => true,
            (GlobalMemberLifecycle::Active, GlobalMemberLifecycle::Paused) => true,
            (GlobalMemberLifecycle::Active, GlobalMemberLifecycle::Retired) => true,
            (GlobalMemberLifecycle::Paused, GlobalMemberLifecycle::Active) => true,
            (GlobalMemberLifecycle::Paused, GlobalMemberLifecycle::Retired) => true,
            _ => false,
        }
    }

    /// Moves the member into the `active` lifecycle when the transition is legal.
    ///
    /// # Errors
    ///
    /// Returns an error when the current lifecycle cannot transition to `active`.
    pub fn activate(&mut self, _actor: &ActorContext) -> Result<(), IdentityError> {
        if !self.can_transition_to(GlobalMemberLifecycle::Active) {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_LIFECYCLE_TRANSITION_INVALID",
                message: format!(
                    "member `{}` cannot transition from `{}` to `active`",
                    self.global_member_id.as_str(),
                    self.lifecycle.as_db()
                ),
            });
        }

        self.apply_lifecycle_transition(GlobalMemberLifecycle::Active);
        Ok(())
    }

    /// Moves the member into the `paused` lifecycle when the transition is legal.
    ///
    /// # Errors
    ///
    /// Returns an error when the reason is blank or when the current lifecycle cannot transition
    /// to `paused`.
    pub fn pause(
        &mut self,
        _actor: &ActorContext,
        reason: impl AsRef<str>,
    ) -> Result<(), IdentityError> {
        if reason.as_ref().trim().is_empty() {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_INVALID_ARGUMENT",
                message: "reason must not be blank".to_string(),
            });
        }
        if !self.can_transition_to(GlobalMemberLifecycle::Paused) {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_LIFECYCLE_TRANSITION_INVALID",
                message: format!(
                    "member `{}` cannot transition from `{}` to `paused`",
                    self.global_member_id.as_str(),
                    self.lifecycle.as_db()
                ),
            });
        }

        self.apply_lifecycle_transition(GlobalMemberLifecycle::Paused);
        Ok(())
    }

    /// Moves the member into the `retired` lifecycle when the transition is legal.
    ///
    /// # Errors
    ///
    /// Returns an error when the reason is blank or when the current lifecycle cannot transition
    /// to `retired`.
    pub fn retire(
        &mut self,
        _actor: &ActorContext,
        reason: impl AsRef<str>,
    ) -> Result<(), IdentityError> {
        if reason.as_ref().trim().is_empty() {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_INVALID_ARGUMENT",
                message: "reason must not be blank".to_string(),
            });
        }
        if !self.can_transition_to(GlobalMemberLifecycle::Retired) {
            return Err(IdentityError::RuleViolation {
                code: "IDENTITY_LIFECYCLE_TRANSITION_INVALID",
                message: format!(
                    "member `{}` cannot transition from `{}` to `retired`",
                    self.global_member_id.as_str(),
                    self.lifecycle.as_db()
                ),
            });
        }

        self.apply_lifecycle_transition(GlobalMemberLifecycle::Retired);
        Ok(())
    }

    /// Links the stable capability-profile id onto the member write model.
    pub fn link_capability_profile(&mut self, capability_profile_id: CapabilityProfileId) {
        if self.capability_profile_id.as_ref() == Some(&capability_profile_id) {
            return;
        }

        self.capability_profile_id = Some(capability_profile_id);
        self.version += 1;
        self.updated_at = current_timestamp();
    }

    /// Links the stable memory-refs id onto the member write model.
    pub fn link_memory_refs(&mut self, memory_refs_id: MemoryRefsId) {
        if self.memory_refs_id.as_ref() == Some(&memory_refs_id) {
            return;
        }

        self.memory_refs_id = Some(memory_refs_id);
        self.version += 1;
        self.updated_at = current_timestamp();
    }

    fn apply_lifecycle_transition(&mut self, target_lifecycle: GlobalMemberLifecycle) {
        self.lifecycle = target_lifecycle;
        self.version += 1;
        self.updated_at = current_timestamp();
    }

    /// Returns the command-side summary for the current member write model.
    pub fn summary(&self) -> GlobalMemberSummary {
        GlobalMemberSummary {
            global_member_id: self.global_member_id.clone(),
            display_name: self.display_name.clone(),
            lifecycle: self.lifecycle,
            main_role_id: self.main_role_id.clone(),
            secondary_role_ids: self.secondary_role_ids.clone(),
            capability_profile_id: self.capability_profile_id.clone(),
            memory_refs_id: self.memory_refs_id.clone(),
        }
    }
}

fn current_timestamp() -> PrimitiveDateTime {
    let now = OffsetDateTime::now_utc();
    PrimitiveDateTime::new(now.date(), now.time())
}
